#*****************************************************************************
# ci.yaml
#
# This file contains the Github actions based CI building and automated
# testing on pushes and pull requests
#
# Author   :  Gary Ash <gary.ash@icloud.com>
# Created  :   2-Aug-2023  7:09pm
# Modified :   3-Aug-2023  1:45pm
#
# Copyright © 2023 By Gee Dbl A All rights reserved.
#*****************************************************************************

name: CI

on:
  push:
    branches: [ "main", "develop" ]

  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    name: Build and Test default scheme
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run testing workflow
        run:  |
            sh BuildEnv/ci.sh